#ifndef _PLC_THREAD_CONFIG_H_
#define _PLC_THREAD_CONFIG_H_ 

#define PLC1_THREAD1_DB_INDEX 4
#define PLC1_THREAD2_DB_INDEX 5
#define PLC1_THREAD3_DB_INDEX 6
#define PLC1_THREAD4_DB_INDEX 7
#define PLC1_THREAD5_DB_INDEX 1
#define PLC1_THREAD6_DB_INDEX 8
#define PLC1_THREAD7_DB_INDEX 9
#define PLC1_THREAD8_DB_INDEX 11
#define PLC1_THREAD9_DB_INDEX 12

#define PLC2_THREAD1_DB_INDEX 1
#define PLC2_THREAD2_DB_INDEX 2
#define PLC2_THREAD3_DB_INDEX 3


#endif
